Repository haxxorsid/referralboard, pull requests merged in 2022-02, with the labels that each got.

#24 Added Login and Home Page UI
  client/package-lock.json
  client/src/App.tsx
  client/src/components/Home/Card.tsx
  client/src/components/Home/Home.tsx
  client/src/components/Login.tsx
  client/src/components/NavBar.tsx
  client/src/components/Register.tsx
Labels: development, sprint1, frontend, Medium

#25 Updated DB Schema with dummy data and added User table APIs
  db/create_table_cards.sql
  db/create_table_companies.sql
  db/create_table_posts.sql
  db/create_table_users.sql
  db/create_table_years_of_experiences.sql
  server/app/app.go
  server/app/init.go
  server/config/config.go
  server/go.mod
  server/handler/cards.go
  server/main.go
  server/models/card.go
  server/models/company.go
  server/models/post.go
  server/models/user.go
  server/models/years_of_experience.go
  server/services/common.go
  server/services/companies.go
  server/services/posts.go
  server/services/users.go
Labels: development, sprint1, backend, Medium

#29 Added UI screenshots for frontend wiki
  images/edit_profile.png
  images/user_registration.png
Labels: documentation, sprint1, Easy

#30 Added APIs for Post table
  server/app/app.go
  server/models/post.go
  server/services/posts.go
Labels: development, sprint1, backend, Medium

#32 Added GitHub issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/user-story-template.md
Labels: documentation, sprint1, Easy

#34 Added Login and Home Page Images
  images/user_home.png
  images/user_login.png
Labels: documentation, sprint1, Easy

#36 Added Navbar Image
  images/navbar.png
Labels: documentation, sprint1, Easy

#37 Added image for branching strategy wiki
  images/branching_strategy.png
Labels: documentation, sprint1, Easy

#50 Fixed Dummy page to fetch posts
  client/package-lock.json
  client/src/App.tsx
  client/src/common/apiService.tsx
  client/src/components/TempHome.tsx
  client/src/types.tsx
Labels: development, sprint1, frontend, Easy, bugfix

#48 Added Epic issue template and updated bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/epic.md
  .github/ISSUE_TEMPLATE/user-story.md
Labels: documentation, sprint1, Easy

#40 Created Sprint1.md
  Sprint1.md
Labels: documentation, sprint1, Easy

#39 Updated README.md
  .github/ISSUE_TEMPLATE/user-story-template.md
  README.md
  client/README.md
Labels: documentation, sprint1, Easy

#62 Updated backend for user registration
  server/app/app.go
  server/app/init.go
  server/go.mod
  server/go.sum
  server/models/post.go
  server/models/user.go
  server/services/companies.go
  server/services/posts.go
  server/services/users.go
  server/services/years_of_experience.go
Labels: development, backend, Easy, sprint2, user-story

#65 Updated backend for login and edit-profile
  server/app/app.go
  server/app/init.go
  server/go.mod
  server/go.sum
  server/models/company.go
  server/models/user.go
  server/models/years_of_experience.go
  server/services/common.go
  server/services/companies.go
  server/services/posts.go
  server/services/users.go
  server/services/years_of_experience.go
Labels: development, backend, Hard, sprint2, user-story

#67 Updated backend for Home (previous posts by you)
  server/app/app.go
  server/app/init.go
  server/models/post.go
  server/services/companies.go
  server/services/posts.go
  server/services/users.go
  server/services/years_of_experience.go
Labels: development, backend, Easy, sprint2
