Repository haxxorsid/referralboard, pull requests merged in 2022-04, with the labels that each got.

#90 Fixed all failing unit test cases after recent backend chanegs
  server/app/app_test.go
  server/config/config.go
Labels: development, backend, Easy, bugfix, sprint3

#93 Sprint3 Demo
  README.md
  Sprint3.md
Labels: documentation, Easy, sprint3

#94 Updated postman collection and SQL
  db/create_table_companies.sql
  db/create_table_posts.sql
  db/create_table_users.sql
  db/create_table_years_of_experiences.sql
  postman_collection.json
Labels: development, backend, Easy, sprint3

#96 Updated frontend for view posts
  client/src/App.tsx
  client/src/common/apiService.tsx
  client/src/common/customValidationRules.tsx
  client/src/components/CreatePost.tsx
  client/src/components/Home/Card.tsx
  client/src/components/Home/Home.tsx
  client/src/components/NotFound.tsx
  client/src/types.tsx
Labels: development, backend, Easy, sprint3

#105 Updated Go CI and fixed lint errors
  .github/workflows/go.yml
  server/.gitignore
  server/app/app.go
  server/app/app_test.go
  server/app/init.go
  server/config/config.go
  server/go.mod
  server/go.sum
  server/main.go
  server/models/company.go
  server/models/post.go
  server/models/user.go
  server/models/years_of_experience.go
  server/services/common.go
  server/services/companies.go
  server/services/posts.go
  server/services/users.go
  server/services/years_of_experience.go
Labels: Easy, devops, sprint4

#106 Added backend unit test cases
  server/app/app_test.go
  server/config/config.go
Labels: backend, Easy, sprint4

#108 Added cypress integration tests
  client/cypress/integration/editProfile.spec.ts
  client/cypress/integration/home.spec.ts
  client/cypress/integration/navbar.spec.ts
  client/cypress/integration/register.spec.ts
Labels: frontend, Easy, sprint4, testing

#107 Added verified tick and updated cypress integration tests
  client/cypress/integration/createPost.spec.ts
  client/cypress/integration/login.spec.ts
  client/src/components/Home/Card.tsx
  client/src/components/NavBar.tsx
  server/app/app_test.go
  server/app/init.go
Labels: development, frontend, Easy, sprint4, testing

#110 Update README.md, created Sprint4.md and updated postman collection
  README.md
  Sprint4.md
  postman_collection.json
Labels: documentation, development, backend, sprint4
