Repository haxxorsid/referralboard, pull requests merged in 2022-01, with the labels that each got.

#6 Updated project description
  README.md
Labels: documentation, planning, sprint1

#11 Frontend Boiler Plate Code
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.test.tsx
  client/src/App.tsx
  client/src/common/apiService.tsx
  client/src/components/Home.css
  client/src/components/Home.tsx
  client/src/components/Login.css
  client/src/components/Login.tsx
  client/src/index.css
  client/src/index.tsx
  client/src/react-app-env.d.ts
  client/src/setupTests.ts
  client/src/types.tsx
  client/tsconfig.json
Labels: development, sprint1, frontend, Easy

#12 Adding Dummy SQL Tables
  .DS_Store
  db/create_schema_app.sql
  db/create_table_cards.sql
Labels: development, sprint1, backend, Easy

#13 Added server boilerplate code
  .DS_Store
  .gitignore
  server/.gitignore
  server/app/app.go
  server/config/config.go
  server/go.mod
  server/go.sum
  server/handler/cards.go
  server/handler/common.go
  server/main.go
  server/models/card.go
Labels: development, sprint1, backend, Medium

#21 Created a registeration page and edit profile page
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.tsx
  client/src/common/theme.tsx
  client/src/components/EditProfile/EditProfile.tsx
  client/src/components/EditProfile/EditProfileForm.tsx
  client/src/components/Home.css
  client/src/components/Login.css
  client/src/components/Login.tsx
  client/src/components/NavBar.tsx
  client/src/components/Register.tsx
  client/src/components/TempHome.tsx
Labels: development, sprint1, frontend, Medium
