Repository haxxorsid/referralboard, pull requests merged in 2022-03, with the labels that each got.

#68 Updated Login and Register Page Front-End
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/common/apiService.tsx
  client/src/common/auth.tsx
  client/src/components/Login.tsx
  client/src/components/NavBar.tsx
  client/src/components/Register.tsx
  client/src/components/TempHome.tsx
  client/src/components/common/Toast.tsx
  client/src/types.tsx
  client/tsconfig.json
Labels: development, frontend, Hard, sprint2

#69 Updated Home and Edit profile frontend
  client/src/common/apiService.tsx
  client/src/components/EditProfile/EditProfile.tsx
  client/src/components/EditProfile/EditProfileForm.tsx
  client/src/components/EditProfile/UpdateEmailForm.tsx
  client/src/components/EditProfile/UpdatePasswordForm.tsx
  client/src/components/EditProfile/UpdateProfileForm.tsx
  client/src/components/Home/Card.tsx
  client/src/components/Home/Home.tsx
  client/src/components/NavBar.tsx
  client/src/components/Register.tsx
  client/src/types.tsx
  client/tsconfig.json
Labels: development, frontend, Medium, sprint2

#70 Added cypress integration tests
  client/cypress.json
  client/cypress/integration/login.spec.ts
  client/cypress/integration/navbar.spec.ts
  client/cypress/integration/register.spec.ts
  client/cypress/tsconfig.json
  client/package-lock.json
  client/package.json
Labels: test, Medium, sprint2

#71 Added register frontend unit tests
  client/package-lock.json
  client/package.json
  client/src/App.test.tsx
  client/src/setupTests.ts
  client/src/tests/Login.test.tsx
  client/tsconfig.json
Labels: test, Easy, sprint2

#72 Updated Users and Posts table SQL Code
  db/create_table_posts.sql
  db/create_table_users.sql
Labels: development, backend, Easy, sprint2

#73 Added unit test cases for Register user API at backend
  server/app/app_test.go
Labels: test, development, backend, Medium, sprint2

#80 Mentioned backend, frontend with member names in README.md
  README.md
Labels: documentation, Easy, sprint3

#84 Updated backend for create post
  server/app/app.go
Labels: development, backend, Easy, sprint3

#85 Updated frontend for create posts
  client/src/App.tsx
  client/src/CreatePost.tsx
  client/src/common/apiService.tsx
  client/src/components/common/customValidationRules.tsx
  client/src/types.tsx
Labels: development, frontend, Easy, sprint3
